name: Build and Package

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore FullScreenExperienceShell/FullScreenExperienceShell.csproj

      - name: Create Temporary Certificate
        run: |
          $cert = New-SelfSignedCertificate -Type Custom -Subject "CN=FullScreenExperienceShell" -KeyUsage DigitalSignature -FriendlyName "FullScreenExperienceShell" -CertStoreLocation "Cert:\CurrentUser\My" -TextExtension @("2.5.29.37={text}1.3.6.1.5.5.7.3.3", "2.5.29.19={text}")
          $password = ConvertTo-SecureString -String "password" -Force -AsPlainText
          Export-PfxCertificate -Cert $cert -FilePath "GitHubActionsWorkflow.pfx" -Password $password
        shell: powershell

      - name: Build and Package
        run: |
          dotnet publish FullScreenExperienceShell/FullScreenExperienceShell.csproj `
            -c Release `
            -r win-x64 `
            --self-contained true `
            /p:AppxPackageSigningEnabled=true `
            /p:PackageCertificateKeyFile="GitHubActionsWorkflow.pfx" `
            /p:PackageCertificatePassword="password" `
            /p:AppxPackageDir="AppxPackages" `
            /p:GenerateAppxPackageOnBuild=true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MSIX-Package
          path: FullScreenExperienceShell/AppxPackages/**/*.msix*
